# Generated by Django 3.1.4 on 2021-01-19 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eCAHapp', '0002_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='game_status',
            field=models.CharField(choices=[('WAITING_START', 'WAITING_START'), ('PLAYING', 'PLAYING'), ('STARTED_BUT_NEED_PLAYERS', 'STARTED_BUT_NEED_PLAYERS'), ('GAME_FINISH', 'GAME_FINISH')], default='WAITING_START', max_length=50),
        ),
    ]
